using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using GestionAdministrative.Models;
using GestionAdministrative.Services.Interfaces;
using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.Linq;
using System;

namespace GestionAdministrative.ViewModels;

/// <summary>
/// ViewModel pour la liste des clients
/// </summary>
public partial class ClientsViewModel : BaseViewModel
{
    private readonly IClientService _clientService;

    // Liste affichée
    [ObservableProperty]
    private ObservableCollection<Client> clients = new();

    // Liste complète pour le filtrage
    private List<Client> _allClients = new();

    [ObservableProperty]
    private Client? selectedClient;

    [ObservableProperty]
    private bool isRefreshing;

    // Recherche
    [ObservableProperty]
    private string? searchQuery;

    public ClientsViewModel(IClientService clientService)
    {
        _clientService = clientService;
        Title = "Clients";
    }

    [RelayCommand]
    private async Task LoadClientsAsync()
    {
        if (IsBusy)
            return;

        try
        {
            IsBusy = true;
            ClearError();

            var clientsList = await _clientService.GetAllClientsAsync();
            _allClients = clientsList ?? new List<Client>();

            // Appliquer filtrage si nécessaire
            FilterClients();
        }
        catch (Exception ex)
        {
            ShowError($"Erreur lors du chargement des clients : {ex.Message}");
        }
        finally
        {
            IsBusy = false;
            IsRefreshing = false;
        }
    }

    [RelayCommand]
    private async Task RefreshAsync()
    {
        IsRefreshing = true;
        await LoadClientsAsync();
    }

    [RelayCommand]
    private async Task AddClientAsync()
    {
        // Navigation vers la page d'ajout
        await Shell.Current.GoToAsync("clientdetail");
    }

    [RelayCommand]
    private async Task SelectClientAsync(Client client)
    {
        if (client == null)
            return;

        SelectedClient = client;
        // Navigation vers la page de détails avec l'ID
        await Shell.Current.GoToAsync($"clientdetail?id={client.Id}");
    }

    [RelayCommand]
    private async Task DeleteClientAsync(Client client)
    {
        if (client == null)
            return;

        try
        {
            // Vérifier si le client a des documents
            var hasDocuments = await _clientService.ClientHasDocumentsAsync(client.Id);

            if (hasDocuments)
            {
                // Afficher une confirmation (à implémenter avec un popup)
                ShowError("Ce client possède des devis ou factures. Êtes-vous sûr de vouloir le supprimer ?");
                return;
            }

            await _clientService.DeleteClientAsync(client);

            // Retirer des listes
            Clients.Remove(client);
            _allClients.RemoveAll(c => c.Id == client.Id);
        }
        catch (Exception ex)
        {
            ShowError($"Erreur lors de la suppression : {ex.Message}");
        }
    }

    // Called when SearchQuery changes (generated by ObservableProperty)
    partial void OnSearchQueryChanged(string? value)
    {
        FilterClients();
    }

    private void FilterClients()
    {
        Clients.Clear();

        if (_allClients == null || _allClients.Count == 0)
            return;

        if (string.IsNullOrWhiteSpace(SearchQuery))
        {
            foreach (var c in _allClients)
                Clients.Add(c);
        }
        else
        {
            var q = SearchQuery.Trim();
            var filtered = _allClients.Where(c =>
                (!string.IsNullOrWhiteSpace(c.Nom) && c.Nom.Contains(q, StringComparison.OrdinalIgnoreCase)) ||
                (!string.IsNullOrWhiteSpace(c.Email) && c.Email.Contains(q, StringComparison.OrdinalIgnoreCase)) ||
                (!string.IsNullOrWhiteSpace(c.Telephone) && c.Telephone.Contains(q, StringComparison.OrdinalIgnoreCase))
            );

            foreach (var c in filtered)
                Clients.Add(c);
        }
    }
}
